# Generated by Django 4.2.6 on 2023-10-16 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='activate',
            new_name='active',
        ),
    ]
