# Generated by Django 4.2.6 on 2023-10-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='lasr_name',
            new_name='last_name',
        ),
    ]
